[package]
name = "axum-sse-periodic-batch"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21", features = ["full"] }
axum = "0.7"
axum-macros = "0.4.0"
log = "0.4"
env_logger = "0.10"
futures = "0.3"
futures-util = "0.3"
rand = { version="0.8", features = ["std"] }
